[target.aarch64-linux-android]
ar = "/home/saba/Code/PunchCard/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/home/saba/Code/PunchCard/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/home/saba/Code/PunchCard/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "/home/saba/Code/PunchCard/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/home/saba/Code/PunchCard/NDK/x86/bin/i686-linux-android-ar"
linker = "/home/saba/Code/PunchCard/NDK/x86/bin/i686-linux-android-clang"

